name: ypay_inventory_ios
description: "YPay iOS SDK"
version: 1.0.3
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  ypay_inventory_platform_interface:
    path: ../ypay_inventory_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      ios:
        package: com.yandex.pay.ypay_inventory_ios
        pluginClass: YpayInventoryIosPlugin

