group 'com.yandex.pay.invenotry.flutter_plugin'
version '1.0-SNAPSHOT'

buildscript {
    ext.kotlin_version = '2.0.20'
    repositories {
        google()
        mavenCentral()
        maven {
            url = uri("https://storage.googleapis.com/r8-releases/raw")
        }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.7.2'
//
//        classpath 'com.android.tools.build:gradle:8.2.0'
//        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:2.0.20'
        classpath 'com.android.tools:r8:8.2.24'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
    if (project.android.hasProperty("namespace")) {
        namespace 'com.yandex.pay.invenotry.flutter_plugin'
    }

    compileSdk 34

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
        test.java.srcDirs += 'src/test/kotlin'
    }

    defaultConfig {
        minSdkVersion 24
    }

    dependencies {
        implementation('com.yandex.pay:widget-badge:2.3.10') // 10
        implementation('com.yandex.pay:widget-info:2.3.10') // 10
        implementation('com.yandex.pay:inventory:2.3.10') // 10
        testImplementation 'org.jetbrains.kotlin:kotlin-test'
        testImplementation 'org.mockito:mockito-core:5.0.0'
    }
}

